Helm 388
OpenNMS/grafana-plugin pull request #653
Opened 2023-03-28 15:35 UTC by Bonrob2

# Pull Request Check Sheet

* [ ] Have you read and followed our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [ ] Have you [made an issue in the OpenNMS issue tracker](https://issues.opennms.org)?<br>If so, you should:
  1. update the title of this PR to be of the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
* [ ] Have you made a comment in that issue which points back to this PR?
* [ ] Have you updated the JIRA link at the bottom of this comment to link to your issue?
* [ ] If this is a new feature, is there documentation?
* [ ] If this is a new feature or substantial change, are there tests that cover it?

# Pull Request Process

One or more reviewers should be assigned to each PR.

If you know that a particular person is subject matter expert in the area your PR affects, feel free to assign one or more reviewers when you create this PR, otherwise reviewers will be assigned for you.

Once the reviewer(s) accept the PR and the branch passes continuous integration in Bamboo, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the Order of the Green Polo) you are welcome to merge the PR.
Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

# External References

* JIRA (Issue Tracker): HELM-388
* Continuous Integration: [CircleCI](https://circleci.com/gh/OpenNMS/opennms-helm)

2023-03-28 17:53 UTC, emarsh1995 requested changes

2023-03-28 17:53 UTC, emarsh1995 commented on docs/modules/ROOT/nav.adoc
> +.Contribute to the {page-component-title}
Perhaps we could shorten this to "Contribute to the Plugin"?

2023-03-28 17:53 UTC, emarsh1995 commented on docs/modules/ROOT/pages/index.adoc
> +Learn how to set up and manage your plugin environment, from installation to creating your first dashboard and using advanced filtering.
```suggestion
Learn how to set up and manage your environment, from installing the plugin to creating your first dashboard and using advanced filtering.
```

2023-03-28 17:53 UTC, emarsh1995 commented on docs/modules/about/pages/introduction.adoc
> +The {page-component-title} is an application that lets you create flexible dashboards to visualize and interact with data stored by OpenNMS.
```suggestion
The {page-component-title} lets you create flexible dashboards to visualize and interact with data stored by OpenNMS.
```

2023-03-28 17:53 UTC, emarsh1995 commented on docs/modules/about/pages/introduction.adoc
> +image::helm-sample-dash.png["The {page-component-title} displaying a sample dashboard, populated with bar graphs and pie charts."]
```suggestion
image::helm-sample-dash.png["Grafana displaying a sample dashboard, populated with bar graphs and pie charts."]
```

2023-03-28 17:53 UTC, emarsh1995 commented on docs/modules/datasources/pages/entity_datasource.adoc
> +. On your plugin dashboard, create a variable named `region`, and set its datasource to an entity datasource that points to your server.
```suggestion
. On your Grafana dashboard, create a variable named `region`, and set its datasource to an entity datasource that points to your server.
```

2023-03-28 17:53 UTC, emarsh1995 commented on docs/modules/getting_started/pages/basic_walkthrough.adoc
> +This section demonstrates how to create a simple dashboard in the {page-component-title}.
```suggestion
This section demonstrates how to create a simple dashboard using the {page-component-title}.
```

2023-03-28 17:53 UTC, emarsh1995 commented on docs/modules/getting_started/pages/basic_walkthrough.adoc
>  You must have the following pre-requisites to create a dashboard:
```suggestion
You must have the following set up to create a dashboard:
```

2023-03-28 17:53 UTC, emarsh1995 commented on docs/modules/reference/pages/how-to-build-with-docker.adoc
> +. Navigate to *Plugins* and enable the *OpenNMS plugin for Grafana*.
```suggestion
. Navigate to *Plugins* and enable the *OpenNMS Plugin for Grafana*.
```

2023-03-28 17:53 UTC, emarsh1995 commented on docs/modules/reference/pages/how-to-build-with-docker.adoc
> +. Log in to your Grafana plugin instance with the default admin credentials (`admin`/`admin`).
```suggestion
. Log in to your Grafana instance with the default admin credentials (`admin`/`admin`).
```

2023-03-28 20:07 UTC, Bonrob2 commented on docs/modules/ROOT/nav.adoc
> +.Contribute to the {page-component-title}
```suggestion
.Contribute to the plugin
```

2023-03-30 13:52 UTC, Bonrob2 commented
@synqotik , note there are still some instances of Helm in this directory, but I"m not sure if I should change them or if they are on the dev side. Please advise.

2023-03-30 15:51 UTC, emarsh1995 requested changes

2023-03-30 15:51 UTC, emarsh1995 commented on docs/modules/about/pages/introduction.adoc
At line 48, there's an instance of {page-component-title} without a preceding "the" that I can't reach to comment on.

2023-03-30 15:51 UTC, emarsh1995 commented on docs/modules/getting_started/pages/basic_walkthrough.adoc
>  ** If the issue persists, make sure the plugin is in the Grafana plugins directory (default: `var/lib/grafana/plugins`).
```suggestion
** If the issue persists, make sure the plugin's files are in the Grafana plugins directory (default: `var/lib/grafana/plugins`).
```

2023-03-30 15:51 UTC, emarsh1995 commented on docs/modules/getting_started/pages/basic_walkthrough.adoc
>  Before you create a dashboard, you must set up the datasource (either xref:datasources:performance_datasource.adoc[performance], xref:datasources:flow_datasource.adoc[flow], or xref:datasources:entit
```suggestion
Before you create a dashboard, you must set up the datasource (xref:datasources:performance_datasource.adoc[performance], xref:datasources:flow_datasource.adoc[flow], or xref:datasources:entity_datasource.adoc[entity]).
```

2023-03-30 15:51 UTC, emarsh1995 commented on docs/modules/getting_started/pages/basic_walkthrough.adoc
>  For this walk-through, we will configure the entity datasource.
```suggestion
For this walk-through, we will configure an entity datasource.
```

2023-03-30 15:51 UTC, emarsh1995 commented on docs/modules/getting_started/pages/migrating_from_opennms_datasource.adoc
>  = Migrate From OpenNMS Data Source Plugin
```suggestion
= Migrate from OpenNMS Data Source Plugin
```

2023-03-30 15:51 UTC, emarsh1995 commented on docs/modules/getting_started/pages/migrating_from_opennms_datasource.adoc
> +. Select the *OpenNMS plugin for Grafana*.
```suggestion
. Select *OpenNMS Plugin for Grafana*.
```

2023-03-30 15:51 UTC, emarsh1995 commented on docs/modules/getting_started/pages/migrating_from_opennms_datasource.adoc
>  ** If the issue persists, make sure the plugin is in the Grafana plugins directory (default: `var/lib/grafana/plugins`).
```suggestion
** If the issue persists, make sure the plugin files are in the Grafana plugins directory (default: `var/lib/grafana/plugins`).
```

2023-03-30 15:51 UTC, emarsh1995 commented on docs/modules/getting_started/pages/migrating_from_opennms_datasource.adoc
> +The plugin provides two datasource types; the OpenNMS Performance type is equivalent to the previous "OpenNMS" datasource.
I think we could move this line up to be the start of the previous paragraph. 🤔

2023-03-30 15:51 UTC, emarsh1995 commented on docs/modules/reference/pages/how-to-build-with-docker.adoc
> +If you want to build a plugin image based on a specific GitHub fork or branch, you can use `--build-arg`:
I think in this case, using the full name makes more sense to reduce ambiguity (i.e. to say we're not referring to _a_ plugin, but _our_ plugin).

```suggestion
If you want to build {page-component-title} based on a specific GitHub fork or branch, you can use `--build-arg`:
```

2023-03-30 15:51 UTC, emarsh1995 commented on docs/modules/reference/pages/how-to-build-with-docker.adoc
> +If you want to use this feature, and you are running the plugin through Docker, you must complete additional configuration.
```suggestion
If you want to use this feature, and you are running the {page-component-title} through Docker, you must complete additional configuration.
```

2023-03-30 15:51 UTC, emarsh1995 commented on src/dashboards/about.json
> +          "content": "# About the OpenNMS Plugin for Grafana\n\nthe plugin is an application that allows users to create flexible dashboards to interact with data stored by OpenNMS. The plugin works
```suggestion
          "content": "# About the OpenNMS Plugin for Grafana\n\nThe plugin is an application that allows users to create flexible dashboards to interact with data stored by OpenNMS. It works with Grafana to display and customize data from OpenNMS. You can create and customize dashboards to display the data you want to see - alarms, outages, key performance indicators - in a way that best meets the needs of your workflow and staff.\n\n## Datasources\n\n * Performance: Retrieve performance metrics (data collection and response time metrics) from the OpenNMS Measurements API.\n * Flow: Retrieve application- and conversation-related metrics derived from flow data stored by OpenNMS.\n * Entity: Retrieve entity model objects from OpenNMS. It currently supports alarms and nodes.\n\n## Dashboard Template Repositories\n\nYou can use these links to find some sample dashboard templates that can be imported into your Grafana instance:\n\n * https://grafana.com/grafana/dashboards?search=opennms\n * https://github.com/opennms-forge/grafana-dashboards\n ",
```

2023-03-31 15:24 UTC, emarsh1995 requested changes
Some pedantic updates and changing instances of "console" to "shell" for syntax highlighting in code blocks.

2023-03-31 15:24 UTC, emarsh1995 commented on docs/modules/installation/pages/plugin.adoc
> +
```suggestion
```

2023-03-31 15:24 UTC, emarsh1995 commented on docs/modules/installation/pages/plugin.adoc
>  == Install via web UI
```suggestion
== Install via Grafana UI
```

2023-03-31 15:24 UTC, emarsh1995 commented on docs/modules/getting_started/pages/migrating_from_opennms_datasource.adoc
> +== Install the plugin
This is me being pedantic, since we're talking about two plugins. :)

```suggestion
== Install the {page-component-title}
```

2023-03-31 15:24 UTC, emarsh1995 commented on docs/modules/getting_started/pages/migrating_from_opennms_datasource.adoc
```suggestion
```

2023-03-31 15:24 UTC, emarsh1995 commented on docs/modules/installation/pages/plugin.adoc
>  [source, console]
I discovered yesterday that "console" isn't recognized as a syntax highlighter, so I'm updating these to "shell" as I come across them.

```suggestion
[source, shell]
```

2023-03-31 15:24 UTC, emarsh1995 commented on docs/modules/installation/pages/source.adoc
>  [source, console]
```suggestion
[source, shell]
```

2023-03-31 15:24 UTC, emarsh1995 commented on docs/modules/installation/pages/source.adoc
>  [source, console]
```suggestion
[source, shell]
```

2023-03-31 15:24 UTC, emarsh1995 commented on docs/modules/installation/pages/source.adoc
>  [source, console]
```suggestion
[source, shell]
```

2023-03-31 15:24 UTC, emarsh1995 commented on docs/modules/installation/pages/upgrading.adoc
>  [source, console]
```suggestion
[source, shell]
```

2023-03-31 15:24 UTC, emarsh1995 commented on docs/modules/reference/pages/how-to-build-with-docker.adoc
>  [source, console]
```suggestion
[source, shell]
```

2023-03-31 15:24 UTC, emarsh1995 commented on docs/modules/reference/pages/how-to-build-with-docker.adoc
>  [source, console]
```suggestion
[source, shell]
```

2023-03-31 15:24 UTC, emarsh1995 commented on docs/modules/reference/pages/how-to-build-with-docker.adoc
>  Refer to Grafana's https://grafana.com/docs/grafana/latest/administration/image_rendering/#remote-rendering-service[Remote rendering service documentation] for more information.
```suggestion
Refer to Grafana's https://grafana.com/docs/grafana/latest/administration/image_rendering/#remote-rendering-service[remote rendering service documentation] for more information.
```

2023-03-31 15:24 UTC, emarsh1995 commented on docs/modules/contributing/pages/developing.adoc
>  [source, console]
```suggestion
[source, shell]
```

2023-03-31 15:24 UTC, emarsh1995 commented on docs/modules/contributing/pages/developing.adoc
>  [source, console]
```suggestion
[source, shell]
```

2023-03-31 15:24 UTC, emarsh1995 commented on docs/modules/contributing/pages/developing.adoc
>  [source, console]
```suggestion
[source, shell]
```

2023-03-31 15:24 UTC, emarsh1995 commented on docs/modules/contributing/pages/developing.adoc
>  [source, console]
```suggestion
[source, shell]
```

2023-03-31 15:24 UTC, emarsh1995 commented on docs/modules/installation/pages/package.adoc
>  [source, console]
```suggestion
[source, shell]
```

2023-03-31 15:24 UTC, emarsh1995 commented on docs/modules/installation/pages/package.adoc
>  [source, console]
```suggestion
[source, shell]
```

2023-04-03 12:51 UTC, Bonrob2 commented
@synqotik , could you review to verify the name changes are correct? Thank you!

2023-04-03 14:26 UTC, synqotik approved these changes
Looks good!

2023-04-04 15:17 UTC, Bonrob2 commented
Replaced references to Helm with appropriate new names and conventions for prose and directories, etc.

2023-04-04 15:24 UTC, merged